In [3]:
# Tratamiento de datos
import pandas as pd
import numpy as np

#Cargamos los tres csv.
coches_2024 = pd.read_csv('datos_ford_2024.csv', index_col = 0)

coches_2023 = pd.read_csv('datos_ford_2023.csv', index_col = 0)

coches_caracteristicas = pd.read_csv('datos_ford_caracteristicas.csv', index_col = 0)

In [4]:
coches_2024.head()

                 VIN   modelo_coche  id_del_vendedor fecha_venta
0  1FABPBLT3JL100001    Ford Fiesta              101  2024-01-15
1  2FADP4EJ9CL100002     Ford Focus              102  2024-02-02
2  3FABP4EJ8CR100003   Ford Mustang              103  2024-01-20
3  4FADS2LJ2CL100004  Ford Explorer              101  2024-02-10
4  5FAHP3K22CL100005    Ford Escape              102  2024-01-05

In [5]:
coches_2023.head()

                 VIN   modelo_coche  id_del_vendedor fecha_venta
0  1FABPBLT3JL200051    Ford Fiesta              113  2023-01-15
1  2FADP4EJ9CL200052     Ford Focus              114  2023-02-02
2  3FABP4EJ8CR200053   Ford Mustang              115  2023-01-20
3  4FADS2LJ2CL200054  Ford Explorer              113  2023-02-10
4  5FAHP3K22CL200055    Ford Escape              114  2023-01-05

In [6]:
coches_caracteristicas.head()

                 VIN  numero_puertas  camara_trasera  sensor_aparcamiento
0  1FABPBLT3JL100001               5            True                 True
1  2FADP4EJ9CL100002               3           False                False
2  3FABP4EJ8CR100003               5            True                 True
3  4FADS2LJ2CL100004               5           False                 True
4  5FAHP3K22CL100005               3           False                False

In [7]:
concat_1 = pd.concat([coches_2024,coches_2023],axis = 1,join = 'inner')
concat_1.head()

,VIN,modelo_coche,id_del_vendedor,fecha_venta,VIN,modelo_coche,id_del_vendedor,fecha_venta
0,1FABPBLT3JL100001,Ford Fiesta,101,2024-01-15,1FABPBLT3JL200051,Ford Fiesta,113,2023-01-15
1,2FADP4EJ9CL100002,Ford Focus,102,2024-02-02,2FADP4EJ9CL200052,Ford Focus,114,2023-02-02
2,3FABP4EJ8CR100003,Ford Mustang,103,2024-01-20,3FABP4EJ8CR200053,Ford Mustang,115,2023-01-20
3,4FADS2LJ2CL100004,Ford Explorer,101,2024-02-10,4FADS2LJ2CL200054,Ford Explorer,113,2023-02-10
4,5FAHP3K22CL100005,Ford Escape,102,2024-01-05,5FAHP3K22CL200055,Ford Escape,114,2023-01-05

In [8]:
concat_0 = pd.concat([coches_2024,coches_2023],axis = 0,join='inner')
concat_0

                  VIN   modelo_coche  id_del_vendedor fecha_venta
0   1FABPBLT3JL100001    Ford Fiesta              101  2024-01-15
1   2FADP4EJ9CL100002     Ford Focus              102  2024-02-02
2   3FABP4EJ8CR100003   Ford Mustang              103  2024-01-20
3   4FADS2LJ2CL100004  Ford Explorer              101  2024-02-10
4   5FAHP3K22CL100005    Ford Escape              102  2024-01-05
..                ...            ...              ...         ...
45  1FABP4BJ3DL200096    Ford Fusion              127  2023-11-18
46  2FABP4AV1FL200097    Ford Bronco              125  2023-11-25
47  3FAHP0JA4CL200098      Ford Edge              126  2023-12-02
48  4FABP4EJ7CL200099    Ford Ranger              127  2023-12-10
49  5FABP4CN0CL200100   Ford Transit              125  2023-12-18

[100 rows x 4 columns]

In [9]:
coches_2023_merge = coches_2023.merge(coches_caracteristicas, how = 'inner', on = 'VIN')
coches_2023_merge

Empty DataFrame
Columns: [VIN, modelo_coche, id_del_vendedor, fecha_venta, numero_puertas, camara_trasera, sensor_aparcamiento]
Index: []

In [10]:
coches_2024_merge = coches_2024.merge(coches_caracteristicas, how = 'inner', on = 'VIN').head(3)
coches_2024_merge

,VIN,modelo_coche,id_del_vendedor,fecha_venta,numero_puertas,camara_trasera,sensor_aparcamiento
0,1FABPBLT3JL100001,Ford Fiesta,101,2024-01-15,5,True,True
1,2FADP4EJ9CL100002,Ford Focus,102,2024-02-02,3,False,False
2,3FABP4EJ8CR100003,Ford Mustang,103,2024-01-20,5,True,True

In [11]:
coches_2024.set_index(["VIN"], inplace = True)
coches_2024.head()

                    modelo_coche  id_del_vendedor fecha_venta
VIN
1FABPBLT3JL100001    Ford Fiesta              101  2024-01-15
2FADP4EJ9CL100002     Ford Focus              102  2024-02-02
3FABP4EJ8CR100003   Ford Mustang              103  2024-01-20
4FADS2LJ2CL100004  Ford Explorer              101  2024-02-10
5FAHP3K22CL100005    Ford Escape              102  2024-01-05

In [12]:
coches_caracteristicas.set_index(["VIN"], inplace = True)
coches_caracteristicas.head()

                   numero_puertas  camara_trasera  sensor_aparcamiento
VIN
1FABPBLT3JL100001               5            True                 True
2FADP4EJ9CL100002               3           False                False
3FABP4EJ8CR100003               5            True                 True
4FADS2LJ2CL100004               5           False                 True
5FAHP3K22CL100005               3           False                False

In [13]:
coches_join = coches_2024.join(coches_caracteristicas, on = 'VIN')
coches_join.head()

,modelo_coche,id_del_vendedor,fecha_venta,numero_puertas,camara_trasera,sensor_aparcamiento
VIN,,,,,,
1FABPBLT3JL100001,Ford Fiesta,101,2024-01-15,5,True,True
2FADP4EJ9CL100002,Ford Focus,102,2024-02-02,3,False,False
3FABP4EJ8CR100003,Ford Mustang,103,2024-01-20,5,True,True
4FADS2LJ2CL100004,Ford Explorer,101,2024-02-10,5,False,True
5FAHP3K22CL100005,Ford Escape,102,2024-01-05,3,False,False