In [4]:
import pandas as pd

In [5]:
input_file = "DatosPandasUniversidades.csv"

In [8]:
df = pd.read_csv(input_file, index_col=2)

In [9]:
df.head()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States

In [11]:
condición_USA = df["country"] == "United States"
universidades_USA = df[condición_USA]
universidades_USA.head()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States
"University of California, Berkeley (UCB)",9,10,90.4,100.0,100.0,20.5,99.9,92.2,63.9,92.4,98.7,100.0,6.7,United States
University of Chicago,10,11,90.3,99.1,95.4,92.5,78.5,81.2,84.4,61.4,98.3,81.7,6.3,United States

In [12]:
condición_90 = df["overall_score"] > 90.0
universidades_90 = df[condición_90]
universidades_90.head()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States

In [13]:
universidades_USA_90 = df[condición_90 & condición_USA]
universidades_USA_90.head()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States
"University of California, Berkeley (UCB)",9,10,90.4,100.0,100.0,20.5,99.9,92.2,63.9,92.4,98.7,100.0,6.7,United States
University of Chicago,10,11,90.3,99.1,95.4,92.5,78.5,81.2,84.4,61.4,98.3,81.7,6.3,United States

In [14]:
#Vamos a crear una columna con la media de la reputación académica y de empleado
calculo_media = (df['academic_reputation'] + df['employer_reputation'])/2
df['mean_reputation_direct_assignment'] = calculo_media

In [15]:
df.head()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country,mean_reputation_direct_assignment
university,,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States,100.0
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom,100.0
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom,100.0
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States,100.0
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States,100.0

In [18]:
df.eval('mean_reputation_direct_assignment.mean()')

np.float64(80.10619047619048)